# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joe/NetBeans-Workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joe/NetBeans-Workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/joe/NetBeans-Workspace && $(CMAKE_COMMAND) -E cmake_progress_start /home/joe/NetBeans-Workspace/CMakeFiles /home/joe/NetBeans-Workspace/work/CMakeFiles/progress.marks
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f CMakeFiles/Makefile2 work/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/NetBeans-Workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f CMakeFiles/Makefile2 work/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f CMakeFiles/Makefile2 work/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f CMakeFiles/Makefile2 work/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/joe/NetBeans-Workspace && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
work/CMakeFiles/gdkmath.dir/rule:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f CMakeFiles/Makefile2 work/CMakeFiles/gdkmath.dir/rule
.PHONY : work/CMakeFiles/gdkmath.dir/rule

# Convenience name for target.
gdkmath: work/CMakeFiles/gdkmath.dir/rule

.PHONY : gdkmath

# fast build rule for target.
gdkmath/fast:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/build
.PHONY : gdkmath/fast

src/intvector2.o: src/intvector2.cpp.o

.PHONY : src/intvector2.o

# target to build an object file
src/intvector2.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/intvector2.cpp.o
.PHONY : src/intvector2.cpp.o

src/intvector2.i: src/intvector2.cpp.i

.PHONY : src/intvector2.i

# target to preprocess a source file
src/intvector2.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/intvector2.cpp.i
.PHONY : src/intvector2.cpp.i

src/intvector2.s: src/intvector2.cpp.s

.PHONY : src/intvector2.s

# target to generate assembly for a file
src/intvector2.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/intvector2.cpp.s
.PHONY : src/intvector2.cpp.s

src/mat4x4.o: src/mat4x4.cpp.o

.PHONY : src/mat4x4.o

# target to build an object file
src/mat4x4.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/mat4x4.cpp.o
.PHONY : src/mat4x4.cpp.o

src/mat4x4.i: src/mat4x4.cpp.i

.PHONY : src/mat4x4.i

# target to preprocess a source file
src/mat4x4.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/mat4x4.cpp.i
.PHONY : src/mat4x4.cpp.i

src/mat4x4.s: src/mat4x4.cpp.s

.PHONY : src/mat4x4.s

# target to generate assembly for a file
src/mat4x4.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/mat4x4.cpp.s
.PHONY : src/mat4x4.cpp.s

src/quaternion.o: src/quaternion.cpp.o

.PHONY : src/quaternion.o

# target to build an object file
src/quaternion.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/quaternion.cpp.o
.PHONY : src/quaternion.cpp.o

src/quaternion.i: src/quaternion.cpp.i

.PHONY : src/quaternion.i

# target to preprocess a source file
src/quaternion.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/quaternion.cpp.i
.PHONY : src/quaternion.cpp.i

src/quaternion.s: src/quaternion.cpp.s

.PHONY : src/quaternion.s

# target to generate assembly for a file
src/quaternion.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/quaternion.cpp.s
.PHONY : src/quaternion.cpp.s

src/vector2.o: src/vector2.cpp.o

.PHONY : src/vector2.o

# target to build an object file
src/vector2.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector2.cpp.o
.PHONY : src/vector2.cpp.o

src/vector2.i: src/vector2.cpp.i

.PHONY : src/vector2.i

# target to preprocess a source file
src/vector2.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector2.cpp.i
.PHONY : src/vector2.cpp.i

src/vector2.s: src/vector2.cpp.s

.PHONY : src/vector2.s

# target to generate assembly for a file
src/vector2.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector2.cpp.s
.PHONY : src/vector2.cpp.s

src/vector3.o: src/vector3.cpp.o

.PHONY : src/vector3.o

# target to build an object file
src/vector3.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector3.cpp.o
.PHONY : src/vector3.cpp.o

src/vector3.i: src/vector3.cpp.i

.PHONY : src/vector3.i

# target to preprocess a source file
src/vector3.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector3.cpp.i
.PHONY : src/vector3.cpp.i

src/vector3.s: src/vector3.cpp.s

.PHONY : src/vector3.s

# target to generate assembly for a file
src/vector3.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector3.cpp.s
.PHONY : src/vector3.cpp.s

src/vector4.o: src/vector4.cpp.o

.PHONY : src/vector4.o

# target to build an object file
src/vector4.cpp.o:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector4.cpp.o
.PHONY : src/vector4.cpp.o

src/vector4.i: src/vector4.cpp.i

.PHONY : src/vector4.i

# target to preprocess a source file
src/vector4.cpp.i:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector4.cpp.i
.PHONY : src/vector4.cpp.i

src/vector4.s: src/vector4.cpp.s

.PHONY : src/vector4.s

# target to generate assembly for a file
src/vector4.cpp.s:
	cd /home/joe/NetBeans-Workspace && $(MAKE) -f work/CMakeFiles/gdkmath.dir/build.make work/CMakeFiles/gdkmath.dir/src/vector4.cpp.s
.PHONY : src/vector4.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gdkmath"
	@echo "... edit_cache"
	@echo "... src/intvector2.o"
	@echo "... src/intvector2.i"
	@echo "... src/intvector2.s"
	@echo "... src/mat4x4.o"
	@echo "... src/mat4x4.i"
	@echo "... src/mat4x4.s"
	@echo "... src/quaternion.o"
	@echo "... src/quaternion.i"
	@echo "... src/quaternion.s"
	@echo "... src/vector2.o"
	@echo "... src/vector2.i"
	@echo "... src/vector2.s"
	@echo "... src/vector3.o"
	@echo "... src/vector3.i"
	@echo "... src/vector3.s"
	@echo "... src/vector4.o"
	@echo "... src/vector4.i"
	@echo "... src/vector4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/joe/NetBeans-Workspace && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

