// This whole thing should be generated in cmake, not a configured template file.

//
// This file is GENERATED from /home/joe/NetBeans-Workspace/work/jfc-cmake/modules/generate_buildinfo/buildinfo.h.in. Do not edit this file directly
//

#ifndef gdkmath_BUILDINFO_H
#define gdkmath_BUILDINFO_H

#define JFC_TARGET_PLATFORM_Linux

const char *const gdkmath_BuildInfo_TargetPlatform = "Linux";
const char *const gdkmath_BuildInfo_ProjectName =    "gdkmath";

const char *const gdkmath_BuildInfo_System =         "Linux-5.0.12-arch2-1-ARCH";
const char *const gdkmath_BuildInfo_SystemVersion =  "5.0.12-arch2-1-ARCH";
const char *const gdkmath_BuildInfo_HostSystemName = "Linux";
const char *const gdkmath_BuildInfo_ProcessorName =  "x86_64";

const char *const gdkmath_BuildInfo_Compiler_ID =      "GNU";
const char *const gdkmath_BuildInfo_Compiler_Version = "8.3.0";

const char *const gdkmath_BuildInfo_BuildFlags_Debug =                "-g3 -gdwarf-2";
const char *const gdkmath_BuildInfo_BuildFlags_MinsizeRelease =       "-Os -DNDEBUG";
const char *const gdkmath_BuildInfo_BuildFlags_Release =              "-O3 -DNDEBUG";
const char *const gdkmath_BuildInfo_BuildFlags_ReleaseWithDebugInfo = "-O2 -g -DNDEBUG";

const char *const gdkmath_BuildInfo_CMake_Version =   "3.14.3";
const char *const gdkmath_BuildInfo_CMake_Generator = "Unix Makefiles";

const char *const gdkmath_BuildInfo_Git_Commit = "eac64afb7962827583c0b80515f9f9418976971a";
const char *const gdkmath_BuildInfo_Git_Date =   "Sat Jun 1 14:49:14 2019";

const char *const gdkmath_BuildInfo_Random_bits128 = "Fe2AQpkCuFcamgo";

//const char *const gdkmath_BuildInfo_FullSet = //All this should be generated straight from script, not a populated template. Its becoming too complex.

#endif

//
// This file is GENERATED from /home/joe/NetBeans-Workspace/work/jfc-cmake/modules/generate_buildinfo/buildinfo.h.in. Do not edit this file directly
//
